### ISSUE TITLE
HD_Instrucción RunScript_The remote server returned an error: (404) Not Found_(v20200212T0856)

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#14]
El archive se colocó en la ruta: C:\Users\1027631\Downloads\Turing_Expo_Cognitive_Testing\App\Local\5590397\0
Al correr el script el log indica lo siguiente:
Error : System.IO.FileNotFoundException: Could not find file 'C:\Users\1027631\Downloads\Turing_Expo_Cognitive_Testing\App\Local\5590397\0\DISTANCIAS.txt'.
File name: 'C:\Users\1027631\Downloads\Turing_Expo_Cognitive_Testing\App\Local\5590397\0\DISTANCIAS.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at MixedReader.MixedExecute.RunScript(String action, Dictionary`2 stepVariable) in C:\Users\gilberto.isida\Source\Repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 7335
   at MixedReader.MixedExecute.selectAccion(List`1 pasos, Dictionary`2 stepVariables) in C:\Users\gilberto.isida\Source\Repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 510

**Comment by CeliaLinares** [comment]
Tampoco funcionan las variantes:
*RunCustomLocal con argumentos
*RunCustomLocal sin argumentos

**Comment by gantonioid** [comment]
@CeliaLinares el script no lo tienes que colocar en la ruta, sino agregarlo a tu proceso con "Add Files"
![image](https://user-images.githubusercontent.com/9600868/76874785-4d709280-6835-11ea-9e36-0eea46993cec.png)


El error 404 es NOT FOUND para cuando se hace un request a servidor remoto (Nuestro file storage), y éste se debe a que no existe el archivo que le estás solicitando.

Estos son los archivos dados de alta en tu proceso
![image](https://user-images.githubusercontent.com/9600868/76874607-07b3ca00-6835-11ea-84a9-ac65e357dbd6.png)

Aquí no existe el archivo que solicitas `DISTANCIAS.txt`

**Comment by CeliaLinares** [comment]
Gracias, pero esto aplica solamente para el RunScript .txt, en las otras instrucciones se hace referencia a otro script en Frida, ahí que me falta realizer para que funcione como se espera?

**Comment by gantonioid** [comment]
Perdona pero no indicas qué es lo que esperas que suceda.

La función de `RunScript` es precisamente para extraer código reutilizable en otro archivo, así simplificas la estructura y legibilidad de tu script principal.
![image](https://user-images.githubusercontent.com/9600868/76877340-d937ee00-6838-11ea-88d3-38978d4fff97.png)

En este ejemplo que te pongo, el archivo Loop.txt tiene que existir dentro del proceso FRIDA como te comenté en mi respuesta anterior. Para eso es el botón "Add Files"

**Comment by CeliaLinares** [comment]
Buen día, aún no puedo utilizar esta instrucción: RunCustomLocal 01_LeerValoresWorkbook
1.-Al cargar el archivo "01_LeerValoresWorkbook", indica lo siguiente y ya no me deja abrir el script.
![Error_Frida_LoadingFiles](https://user-images.githubusercontent.com/60754307/77184783-e998d480-6a95-11ea-8b57-6412719b3001.png)

**Comment by gantonioid** [comment]
Los nombres de archivo no pueden empezar con números, además evita tener caracteres especiales. Ya corregí tu estructura.
![image](https://user-images.githubusercontent.com/9600868/77187920-d3d9de00-6a9a-11ea-92ed-79341dde77ec.png)

**Comment by CeliaLinares** [comment]
ok, lo revise, gracias

**Comment by CeliaLinares** [comment]
Me indica:
RunCustomLocal LeerValoresWorkbook.txt : Error
3/20/2020 11:10:54 AM - Error : Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 722
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 649
   at Microsoft.WindowsAzure.Storage.File.CloudFileDirectory.<>c__DisplayClasse.<ListFilesAndDirectories>b__d(IContinuationToken token) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\File\CloudFileDirectory.cs:line 947
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.<LazyEnumerable>d__0`1.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\Util\CommonUtility.cs:line 322
   at MixedReader.MixedExecute.RunCustomLocal(String ProjectName, String action) in C:\Users\gilberto.isida\Source\Repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 7543
   at MixedReader.MixedExecute.selectAccion(List`1 pasos, Dictionary`2 stepVariables) in C:\Users\gilberto.isida\Source\Repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 547
Request Information
RequestID:23244611-f01a-010f-7fda-fe464d000000
RequestDate:Fri, 20 Mar 2020 17:11:03 GMT
StatusMessage:The specified resource does not exist.
ErrorCode:ResourceNotFound
ErrorMessage:The specified resource does not exist.
RequestId:23244611-f01a-010f-7fda-fe464d000000
Time:2020-03-20T17:11:04.1664018Z

3/20/2020 11:10:54 AM - RunCustomLocal LeerValoresWorkbook.txt : Error

Adjunto el log completo:
[log_RunScript_032020.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/4360969/log_RunScript_032020.txt)

**Comment by gantonioid** [comment]
Celia... RunCustomLocal es para cuando quieres correr un `.exe` `.jar` `.groovy`

Lo que debes de usar es RunScript

**Comment by CeliaLinares** [comment]
Gracias, estaba probando todas las opciones buscando que funcionara alguna y no leí que hubiera diferencia. ya funciona con RunScript.
