### ISSUE TITLE
Aplicación Frida Turing no abre

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#26]
Hola buenos días, solicitando su apoyo para restablecer la aplicación.

El día de hoy aprox a las 9.45am la aplicación Frida Turing dejó de funcionar. Al cerrar e iniciar de nuevo la aplicación solo aparece el logo de Frida y se cierra.

Revisando el archivo AppLog.txt muestra lo siguiente:

9/10/2021 10:32:04 AM - The remote server returned an error: (500) Internal Server Error.
9/10/2021 10:32:04 AM -    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at TuringExpo.MainWindow.PasswordUserValidation(String mail)
   at TuringExpo.MainWindow..ctor()

**Comment by raulhgit** [comment]
Ya se restableció, gracias
